<a href="https://colab.research.google.com/github/Tejaswidarsi/ML-1/blob/main/Ass_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [ ]:
import numpy as np
import math

#compute the mean and variance of the elements present in the array.

_Mean_ represents the average value of the elements in the vector. It provides information about the central tendency of the data.

_Variance_ measures the spread or dispersion of the data points around the mean. It quantifies how far each element in the vector is from the mean.


In [ ]:

N=10
vector = np.array([2,9,10,5,7,1,12,17,18,6])
mean  = np.mean(vector)
diff =  (vector - mean)**2
sample_variance = np.sum(diff)/(N-1)
pop_variance = np.sum(diff)/N
print(f"vector :{vector}")
print(f"mean:{mean:.2f}")
print(f"sample variance:{sample_variance:.2f}")
print(f"population variance:{pop_variance:.2f}")

vector :[ 2  9 10  5  7  1 12 17 18  6]
mean:8.70
sample variance:32.90
population variance:29.61


#compute the Covariance between two vectors
_Covariance_ measures the degree to which two variables change together. A positive covariance indicates that the two variables tend to move in the same direction, while a negative covariance indicates they move in opposite directions.

In [ ]:
V1 =  np.array([3,6,7,10,6,9])
V2 =  np.array([5,9,8,1,2,4])
n= len( V1)
cov = 0.0
mx = np.mean(V1)
my = np.mean(V2)
print(mx,my)
for i in range(n):
  x_i= V1[i]
  y_i = V2[i]
  pro= (x_i - mx)*(y_i-my)
  cov+=pro
r=cov/(n-1)
print(f"covariance:{cov:.3f}")

6.833333333333333 4.833333333333333
covariance:-15.167


#Correlation between Two Vectors




_Correlation_ is a normalized measure of covariance that describes the strength and direction of a linear relationship between two variables. The correlation coefficient ranges from -1 (perfect negative correlation) to +1 (perfect positive correlation)

In [ ]:
V1 =  np.array([11,2,13,10,21,9])
V2 =  np.array([14,6,18,1,9,3])
n= len( V1)
cov = 0.0
cor =0.0
mx = np.mean(V1)
my = np.mean(V2)
print(mx,my)
vx = np.var(V1)
vy = np.var(V2)
print(vx,vy)
for i in range(n):
  x_i= V1[i]
  y_i = V2[i]
  pro= (x_i - mx)*(y_i-my)
  cov+=pro
r=cov/(n-1)
d=math.sqrt(vx*vy)
cor = r/d
print(f"covariance:{cov:.3f}")
print(f"correlation:{cor:.3f}")

11.0 8.5
31.666666666666668 35.583333333333336
covariance:65.000
correlation:0.387


#Covariance and Correlation Matrices

_Covariance Matrix_ is a matrix that shows the covariance between all pairs of features in the dataset.
_Correlation Matrix_ is a matrix that shows the correlation coefficients between all pairs of features in the dataset.

In [ ]:
Matrix = np.array([[21,11,8],[3,17,9],[18,4,12],[11,0,13]])
print(Matrix)
cov_matrix = np.cov(Matrix, bias=False)
cor_matrix = np.corrcoef(Matrix)
print(f"covariance matrix:{cov_matrix}")
print(f"correlation matrix:{cor_matrix}")

[[21 11  8]
 [ 3 17  9]
 [18  4 12]
 [11  0 13]]
covariance matrix:[[ 46.33333333 -32.33333333  32.33333333   7.5       ]
 [-32.33333333  49.33333333 -49.33333333 -41.        ]
 [ 32.33333333 -49.33333333  49.33333333  41.        ]
 [  7.5        -41.          41.          49.        ]]
correlation matrix:[[ 1.         -0.6762908   0.6762908   0.15740425]
 [-0.6762908   1.         -1.         -0.8339031 ]
 [ 0.6762908  -1.          1.          0.8339031 ]
 [ 0.15740425 -0.8339031   0.8339031   1.        ]]
